### ISSUE TITLE
is i3 window manager like tilling possible?

### ISSUE THREAD

**Issue by Michael-Jing** [dsanson/hs.tiling#7]
Hi, I like the i3 tilling window manager under linux very much. So I am wondering is it possible to do i3 like tilling in hammperspoon, ie, if there is only one window in the current workspace, make it maximum size, if there are more than 1 window in the current workspace, make them equally splitted.

**Comment by dsanson** [comment]
Should be pretty straightforward! Not something I am going to add to hs.tiling, mostly because I've stopped using it in favor of using kwm for window management.

**Comment by Michael-Jing** [comment]
Thank you for your reply, I found that kwm fit my needs too.
