### ISSUE TITLE
Added couple of layouts, do you want to have them in master? 

### ISSUE THREAD

**Issue by auraz** [dsanson/hs.tiling#9]
Can do PR then.

**Comment by dsanson** [comment]
I haven't used Hammerspoon in a few years, so probably am not the right person to continue to maintain this. If people are still using it, I should probably change the README to point to an active fork.

**Comment by auraz** [comment]
Ah, Ok, nvm then.
Just curious what are you using instead?

Alexander
///


1 бер. 2019 р. о 00:34 David Sanson <notifications@github.com> пише:

**Comment by dsanson** [comment]
https://github.com/koekeishiya/chunkwm and https://github.com/koekeishiya/skhd and a little bit of http://tracesof.net/uebersicht/

**Comment by auraz** [comment]
Thanks, automatic tiling is what I was looking for a long time :)

PS: Tried it, actually looks great :)

Thank you :)
